---
title: "bayesian simple linear regression"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(BAS)
library(ggplot2)
data(bodyfat)
summary(bodyfat)
```
```{r}
plot(Bodyfat~Abdomen,data = bodyfat,xlab = "abdomen circumference(cm)", col = "steelblue", pch = 16, main = "")
bodyfat.lm = lm(Bodyfat~Abdomen,data = bodyfat)
summary(bodyfat.lm)
beta = coef(bodyfat.lm)
abline(beta,lwd = 4, col = 1)
```
```{r}
ggplot(bodyfat.lm,aes(x = .fitted,y = .resid))+
  geom_point(col = "steelblue")+
  geom_hline(yintercept = 0, linetype = "dashed")
```
```{r}
plot(bodyfat.lm,which = 2)
ggplot(bodyfat.lm,aes(sample = .resid))+
  stat_qq()
```

```{r}
out = summary(bodyfat.lm)$coef[,1:2]
out
```
```{r}
out = cbind(out,confint(bodyfat.lm))
colnames(out) = c("posterior mean", "sd","2.5","97.5")
round(out,2)
```
```{r}
x = bodyfat$Abdomen
y = bodyfat$Bodyfat
xnew = seq(min(x),max(x),length.out = 100)
ynew = data.frame(predict(bodyfat.lm,newdata = data.frame(Abdomen = xnew),interval = "confidence",level = 0.95))
plot(x,y,xlab = "abdomen",ylab ="bodyfat",col = "steelblue",pch = 16)
lines(ynew$lwr~xnew,lty = 2,lwd  =3,col = "darkgrey")
lines(ynew$upr~xnew,lty = 2,lwd  =3,col = "darkgrey")
abline(bodyfat.lm,col = "orange")
ynew = data.frame(predict(bodyfat.lm,newdata = data.frame(Abdomen = xnew),interval = "prediction",level = 0.95))
lines(ynew$lwr~xnew,lty = 3,lwd  =3,col = "darkgrey")
lines(ynew$upr~xnew,lty = 3,lwd  =3,col = "darkgrey")
points(bodyfat[39,"Abdomen"],bodyfat[39,"Bodyfat"],col = "orange",cex = 5)
legend(110,20,legend = c("posterior mean","95% CI for mean","95% CI for predictions"),col = c("orange",rep("darkgrey",2)),lwd = 3,lty = c(1,2,3))
```


```{r}
Bayes.outlier.prob <- function(lmobj, k=3) {
	e <- residuals(lmobj)
	h <- hatvalues(lmobj)
	Q <- qr.Q(lmobj$qr)
	alpha <- (lmobj$df.residual)/2
	rate <- (lmobj$df.residual*(summary(lmobj)$sigma)^2)/2 
	n <- length(e)
	pr <- rep(0,n)
	prjoint <- matrix(0,n,n)
	for (i in 1:n){
          pr[i] = integrate(outlier.prob,lower=0,upper=Inf,
                    ehat=e[i],hii=h[i],alpha=alpha,rate=rate,nsd=k)$value
        }
return(list(e=e,hat=h,prob.outlier=pr))
}

outlier.prob <- function(phi, ehat,hii,alpha,rate, nsd) {
	z1 <- (nsd - ehat*sqrt(phi))/sqrt(hii)
	z2 <- (- nsd - ehat*sqrt(phi))/sqrt(hii)
	pr.phi <- (1 - pnorm(z1) + pnorm(z2))*dgamma(phi,shape=alpha, rate=rate)
	return(pr.phi)}

bivoutlier.prob <- function(phi, ehati,ehatj,hii,hjj, rhoij, alpha,rate, nsd) {

        z1i = (nsd - ehati*sqrt(phi))/sqrt(hii)
	z2i = (- nsd - ehati*sqrt(phi))/sqrt(hii)
	z1j = (nsd - ehatj*sqrt(phi))/sqrt(hjj)
	z2j = (- nsd - ehatj*sqrt(phi))/sqrt(hjj)
        corr.neg = corr.pos =  diag(2)
        corr.pos[1,2] = corr.pos[2,1] = rhoij
        corr.neg[1,2] = corr.neg[2,1] = -rhoij
        B11 = apply(cbind(z1i,z1j), 1,
                    function(x){pmvnorm(lower=x, corr=corr.pos)} )
        B22 = apply(cbind(-z2i,-z2j), 1,
                    function(x){pmvnorm(lower=x, corr=corr.pos)})
        B12 = apply(cbind(z1i,-z2j), 1,
                    function(x){pmvnorm(lower=x, corr=corr.neg)})
        B21 = apply(cbind(-z2i,z1j), 1,
                    function(x){pmvnorm(lower=x, corr=corr.neg)})
        
        binorm = B11 + B22 + B12 + B21
        binorm[is.na(binorm)] = 0
#	binorm <-  (pmvnorm(-z1i,-z1j,corr=corr.pos) +
#                   pmvnorm(z2i,z2j,corr=corr.pos) - 
#	            pmvnorm(-z1i,z2j,corr=corr.neg) -
#                   pmvnorm(z2i,-z1j, corr=corr.neg))
	pr.phi <- binorm*dgamma(phi,shape=alpha, rate=rate)
	return(pr.phi)}


Bayes.outlier.prob.joint <- function(lmobj, k=3, joint=FALSE) {
	e <- residuals(lmobj)
	h <- hatvalues(lmobj)
	Q <- qr.Q(lmobj$qr)
	alpha <- (lmobj$df.residual)/2
	rate <- (lmobj$df.residual*(summary(lmobj)$sigma)^2)/2 
	n <- length(e)
	prjoint <- matrix(0,n,n)
	for (i in 1:n){
          j = 1
          while (j < i ) {
           corrij = sum(Q[i,]*Q[j,])/sqrt(h[i]*h[j]) 
           prjoint[i,j] = integrate(bivoutlier.prob,lower=0,upper=Inf,
                   ehati=e[i],ehatj=e[j],hii=h[i],hjj=h[j],
                   rhoij=corrij,alpha=alpha,rate=rate,nsd=k)$value
           prjoint[j,i] =  prjoint[i,j]
           j = j + 1
           print(c(i,j,prjoint[j,i]))
         }
        }
return(prjoint)
}

```

```{r}
library(mvtnorm)
outliers = Bayes.outlier.prob(bodyfat.lm)
prob.39 = outliers$prob.outlier[39]
prob.39
```

```{r}
n = nrow(bodyfat)
(1-(2*pnorm(-3)))^n
```
```{r}
1-(1-(2*pnorm(-3)))^n
```
```{r}
k = qnorm(.5+.5*.95^(1/n))
k
```
```{r}
outliers.no = Bayes.outlier.prob(bodyfat.lm,k = k)
prob.no.39 = outliers.no$prob.outlier[39]
prob.no.39
```

```{r}
2*pnorm(-k)
```

